/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/shared/theme/ds/auditoria-theme.ts
 * Command: astryx theme build src/shared/theme/ds/auditoria-theme.ts --out src/shared/theme/ds/auditoria.css
 * Generated: 2026-07-27T22:59:20.904Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    soft: true;
  }
}
