/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/shared/theme/ds/auditoria-theme.ts
 * Command: astryx theme build src/shared/theme/ds/auditoria-theme.ts --out src/shared/theme/ds/auditoria.css
 * Generated: 2026-07-29T15:59:30.541Z
 */

/// <reference path="./auditoria.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const auditoriaTheme: DefinedTheme;
